import { makeTest, expect } from '../fixtures/app'
import { gotoModule } from '../helpers/nav'
import { join } from 'path'
import { existsSync, readFileSync, writeFileSync } from 'fs'
import Database from 'better-sqlite3'
const test = makeTest({ transformSeed: seed => ({ ...seed, workspaces: [...seed.workspaces, { ...seed.workspaces[0]!, id: 'assets-space-B', name: '隔离空间B', path: join(seed.workspaces[0]!.path, '..', '隔离空间B') }] }) })

test('资产三形态、版本、分类标签、归档删除与退出取消的真实闭环', async ({ page, electronApp, launched }) => {
  test.setTimeout(180_000)
  await gotoModule(page, 'assets')
  await expect(page.getByRole('button', { name: '新建资产', exact: true }).first()).toBeEnabled()
  const context = await page.evaluate(() => window.electronAPI!.assets.context())
  expect(context.ok).toBe(true)
  const db = join(launched.tempHome.home, 'Mimir', '科研空间', '.mimir', 'assets', 'assets.db')
  expect(existsSync(db)).toBe(true)
  // Create an inline asset and then edit only metadata: no new body version.
  await page.getByRole('button', { name: '新建资产', exact: true }).first().click()
  await page.getByLabel('名称', { exact: true }).fill('E2E文本')
  await page.getByLabel('正文', { exact: true }).fill('  原文\n\n')
  await page.getByLabel('标签（逗号分隔）').fill('E2E标签A,E2E标签B')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  const detail = page.getByRole('article', { name: '资产详情' })
  await expect(detail.getByRole('heading', { name: 'E2E文本' })).toBeVisible()
  expect(await detail.locator('pre').first().textContent()).toBe('  原文\n\n')
  await detail.getByRole('button', { name: '编辑资产' }).click()
  await page.getByLabel('摘要').fill('metadata only')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(detail).toContainText('metadata only')
  await expect(detail).toContainText('v1')
  await detail.getByRole('button', { name: '编辑资产' }).click()
  await page.getByLabel('正文', { exact: true }).fill('')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(detail).toContainText('v2')
  await detail.getByRole('button', { name: '历史版本' }).click()
  await page.getByLabel('比较旧版本').selectOption({ label: 'v1' })
  await page.getByLabel('比较新版本').selectOption({ label: 'v2' })
  await page.getByRole('button', { name: '比较版本', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('原文')
  await page.getByRole('button', { name: '回滚 v1', exact: true }).click()
  await expect(detail).toContainText('v3')
  expect(await detail.locator('pre').first().textContent()).toBe('  原文\n\n')
  // Native app.quit cancellation must leave SQLite/IPC usable, with the draft intact.
  await detail.getByRole('button', { name: '编辑资产' }).click()
  await page.getByLabel('名称', { exact: true }).fill('未保存草稿')
  await electronApp.evaluate(({ app }) => app.quit())
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('未保存草稿')
  expect(await page.evaluate(async () => {
    const context = await window.electronAPI!.assets.context()
    return context.ok && (await window.electronAPI!.assets.list(context.context)).ok
  })).toBe(true)
  // Real React navigation request while a dirty modal is active; cancel then discard.
  await page.getByRole('button', { name: '总览', exact: true, includeHidden: true }).first().evaluate(button => (button as HTMLButtonElement).click())
  await expect(page.getByRole('heading', { name: '存在未保存的资产编辑' })).toBeVisible()
  await page.getByRole('button', { name: '留在这里', exact: true }).click()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('未保存草稿')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '丢弃后离开' }).click()
  // Category edit and tag governance are exercised through the actual UI.
  await page.getByRole('button', { name: '新建分类', exact: true }).click()
  await page.getByLabel('分类名称').fill('E2E分类')
  await page.getByRole('button', { name: '保存分类', exact: true }).click()
  await expect(page.getByRole('button', { name: /E2E分类/ }).first()).toBeVisible()
  await page.getByRole('button', { name: '编辑分类 E2E分类', exact: true }).click()
  await page.getByLabel('分类名称').fill('E2E分类改名')
  await page.getByRole('button', { name: '保存分类', exact: true }).click()
  await page.getByRole('button', { name: '编辑分类 E2E分类改名', exact: true }).click()
  await page.getByRole('button', { name: '读取分类删除影响', exact: true }).click()
  await page.getByLabel('确认删除空分类').check()
  await page.getByRole('button', { name: '删除分类', exact: true }).click()
  await expect(page.getByRole('button', { name: '编辑分类 E2E分类改名', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '标签管理', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: 'E2E标签A', exact: true }).click()
  await page.getByRole('button', { name: '读取治理影响' }).click()
  await expect(page.getByRole('dialog')).toContainText('影响 1 条资产')
  await page.getByLabel('合并到标签').selectOption({ label: 'E2E标签B' })
  await page.getByLabel('确认上述标签影响').check()
  await page.getByRole('button', { name: '合并标签', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('button', { name: 'E2E标签A', exact: true })).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: 'Close' }).click()
  // External link stays editable; no external browser/network is opened by this test.
  await page.getByRole('button', { name: '新建资产', exact: true }).first().click()
  await page.getByLabel('名称', { exact: true }).fill('E2E外链')
  await page.getByLabel('存储形态').selectOption('external_link')
  await page.getByLabel('外链地址').fill('https://example.com/reference')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(detail).toContainText('https://example.com/reference')
  // File dialogs select only synthetic input and an absent output inside our temp root.
  const input = join(launched.tempHome.root, 'source.bin'), output = join(launched.tempHome.root, 'download.bin')
  const bytes = Buffer.from([0, 255, 10, 13, 44])
  writeFileSync(input, bytes)
  await electronApp.evaluate(({ dialog }, paths) => {
    dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [paths.input] })
    dialog.showSaveDialog = async () => ({ canceled: false, filePath: paths.output })
  }, { input, output })
  await page.getByRole('button', { name: '新建资产', exact: true }).first().click()
  await page.getByLabel('名称', { exact: true }).fill('E2E文件')
  await page.getByLabel('存储形态').selectOption('file')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await detail.getByRole('button', { name: '导入新文件版本' }).click()
  await expect(detail).toContainText('文件可用')
  await detail.getByRole('button', { name: '下载当前文件' }).click()
  await expect.poll(() => existsSync(output)).toBe(true)
  expect(readFileSync(output)).toEqual(bytes)
  await detail.getByRole('button', { name: '归档资产' }).click()
  await expect(detail.getByRole('button', { name: '恢复资产' })).toBeVisible()
  await expect(detail).toContainText('文件可用')
  await detail.getByRole('button', { name: '恢复资产' }).click()
  await detail.getByRole('button', { name: '永久删除', exact: true }).click()
  await page.getByLabel('我确认删除上述资产及历史').check()
  await page.getByRole('dialog').getByRole('button', { name: '永久删除', exact: true }).click()
  await expect(detail).toHaveCount(0)
  await page.setViewportSize({ width: 850, height: 720 })
  await page.getByRole('button', { name: /E2E文本/ }).click()
  await expect(page.getByRole('button', { name: '返回列表' })).toBeVisible()
  await page.getByRole('button', { name: '返回列表' }).click()
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  await page.screenshot({ path: '../../.git/codex-integration/assets-ui-dark-narrow.png' })
  for (const module of ['library', 'paper', 'figures', 'ledger', 'meetings', 'servers', 'venues', 'chat'] as const) await gotoModule(page, module)
})

test('切空间取消与保存冲突不丢草稿；成功切换后旧epoch失效、新空间无旧资产', async ({ page, electronApp }) => {
  await gotoModule(page, 'assets')
  await page.getByRole('button', { name: '新建资产', exact: true }).first().click()
  await page.getByLabel('名称', { exact: true }).fill('E2E冲突')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('article', { name: '资产详情' })).toContainText('E2E冲突')
  const old = await page.evaluate(async () => {
    const context = await window.electronAPI!.assets.context()
    if (!context.ok) throw new Error(context.message)
    const page = await window.electronAPI!.assets.list({ ...context.context, page: 1, pageSize: 30 })
    if (!page.ok) throw new Error(page.message)
    return { ...context.context, assetId: page.page.items.find(a => a.name === 'E2E冲突')!.id }
  })
  await page.getByRole('button', { name: '编辑资产', exact: true }).click()
  await page.getByLabel('名称', { exact: true }).fill('冲突草稿')
  await page.evaluate(async old => {
    const current = await window.electronAPI!.assets.get(old)
    if (!current.ok) throw new Error(current.message)
    const update = await window.electronAPI!.assets.update({ ...old, expectedRevision: current.asset.revision, patch: { notes: 'external revision' } })
    if (!update.ok) throw new Error(update.message)
  }, old)
  // Native save-before-close fails against the now-stale revision and keeps the window alive.
  await electronApp.evaluate(({ dialog, app }) => { dialog.showMessageBoxSync = () => 1; app.quit() })
  await expect(page.getByRole('alert')).toContainText('输入已保留')
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('冲突草稿')
  await electronApp.evaluate(({ dialog }) => { dialog.showMessageBoxSync = () => 0 })
  async function requestB() {
    await page.getByTitle('切换科研空间').evaluate(button => (button as HTMLButtonElement).click())
    await page.getByRole('button', { name: '隔离空间B', exact: true, includeHidden: true }).evaluate(button => (button as HTMLButtonElement).click())
  }
  await requestB()
  await page.getByRole('button', { name: '留在这里', exact: true }).click()
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('冲突草稿')
  await requestB()
  await page.getByRole('button', { name: '保存后离开', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('输入已保留')
  await expect(page.getByLabel('名称', { exact: true })).toHaveValue('冲突草稿')
  await requestB()
  await page.getByRole('button', { name: '丢弃后离开', exact: true }).click()
  await expect(page.getByText('科研空间：assets-space-B', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: /E2E冲突/ })).toHaveCount(0)
  const result = await page.evaluate(old => window.electronAPI!.assets.get(old), old)
  expect(result.ok).toBe(false)
  if (!result.ok) expect(result.code).toBe('SPACE_CHANGED')
})

test('原生保存后关闭落盘完整正文，再清理后台并退出进程', async ({ page, electronApp, launched }) => {
  await gotoModule(page, 'assets')
  await page.getByRole('button', { name: '新建资产', exact: true }).first().click()
  await page.getByLabel('名称', { exact: true }).fill('E2E关闭保存')
  await page.getByRole('button', { name: '保存', exact: true }).click()
  await page.getByRole('button', { name: '编辑资产', exact: true }).click()
  await page.getByLabel('正文', { exact: true }).fill('  保存后退出\n\n')
  const process = electronApp.process()
  await electronApp.evaluate(({ dialog, app }) => { dialog.showMessageBoxSync = () => 1; app.quit() })
  await expect.poll(() => process.exitCode).not.toBeNull()
  // Reopen only the synthetic DB using the Node ABI; read-only and closed before fixture cleanup.
  const store = JSON.parse(readFileSync(join(launched.tempHome.home, '.mimir', 'store.json'), 'utf8'))
  const space = store['workspaces:list'].find((space: { id: string }) => space.id === store.activeWorkspaceId)
  const db = new Database(join(space.path, '.mimir', 'assets', 'assets.db'), { readonly: true })
  try {
    expect(db.prepare('SELECT v.content FROM asset a JOIN asset_version v ON v.id=a.current_version_id WHERE a.name=?').get('E2E关闭保存')).toEqual({ content: '  保存后退出\n\n' })
  } finally { db.close() }
})
