import { useRef, useState } from 'react'
import { Button } from '@/components/ui/button'
import type { AssetCategory, AssetTag, AssetSummary, AssetBatchPreview, WorkspaceRequest } from '../../../../shared/assetsContracts'
import { assetsApi } from './assetsApi'
import { useAssetPreview } from './useAssetPreview'
import { AssetError, AssetField, AssetModal, controlClass, errorMessage, useAssetsEditorGuard } from './assetsUi'
export function BatchEditDialog({scope,assets,categories,tags,write,onChanged,onClose}:{scope:WorkspaceRequest;assets:AssetSummary[];categories:AssetCategory[];tags:AssetTag[];write:<T>(fn:(s:WorkspaceRequest)=>Promise<T>)=>Promise<T>;onChanged:()=>void;onClose:()=>void}) {
  const [category,setCategory]=useState(''),[add,setAdd]=useState(''),[remove,setRemove]=useState<number[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),preview=useAssetPreview<AssetBatchPreview>(),saving=useRef(false)
  const request=()=>({...scope,assets:assets.map(a=>({assetId:a.id,expectedRevision:a.revision})),...(category?{category}:{}),addTagNames:add.split(/[,，]/).map(s=>s.trim()).filter(Boolean),removeTagIds:remove})
  useAssetsEditorGuard({isDirty:()=>false,isBusy:()=>saving.current,save:async()=>false,discard:onClose})
  async function commit(){if(saving.current||!preview.value)return;saving.current=true;setBusy(true);setError('');try{await write(s=>assetsApi.commitBatch({...request(),...s,previewToken:preview.value!.previewToken}));onChanged();onClose()}catch(error){setError(`${errorMessage(error)}；选择与输入已保留，请刷新后重新选择或预览。`);preview.clear()}finally{saving.current=false;setBusy(false)}}
  return <AssetModal title={`批量整理 ${assets.length} 项`} onClose={()=>{if(!saving.current)onClose()}}><div className="space-y-3"><p className="text-sm">先预览影响范围，再确认。任何陈旧选择会整批拒绝；正文与文件历史保留。</p><AssetField label="目标分类"><select className={controlClass} disabled={busy} value={category} onChange={e=>{setCategory(e.target.value);preview.clear()}}><option value="">保持原分类</option>{categories.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></AssetField><AssetField label="新增标签（逗号分隔）"><input className={controlClass} value={add} disabled={busy} onChange={e=>{setAdd(e.target.value);preview.clear()}} /></AssetField><fieldset disabled={busy}><legend className="text-sm">移除标签</legend><div className="flex flex-wrap gap-2">{tags.map(t=><label key={t.id} className="text-sm"><input type="checkbox" checked={remove.includes(t.id)} onChange={e=>{setRemove(r=>e.target.checked?[...r,t.id]:r.filter(id=>id!==t.id));preview.clear()}} /> {t.name}</label>)}</div></fieldset><Button variant="outline" disabled={busy||preview.loading} onClick={()=>void preview.read(async()=>(await assetsApi.previewBatch(request())).preview)}>预览批量影响</Button><AssetError message={error||preview.error}/>{preview.value&&<section aria-label="批量影响"><p>将修改 {preview.value.changed} 项</p>{preview.value.rows.map(r=><p key={r.assetId} className="text-sm">{r.name}：{r.beforeCategory} → {r.afterCategory}；标签 {r.beforeTags.join('、')} → {r.afterTags.join('、')}</p>)}</section>}<div className="flex justify-end gap-2"><Button disabled={busy} variant="outline" onClick={onClose}>取消</Button><Button disabled={busy||!preview.value} onClick={()=>void commit()}>确认批量修改</Button></div></div></AssetModal>
}
